package net.electra.net;

public enum DisconnectReason
{
    UNKNOWN,
    DATA_TRANSFER_TIMEOUT,
    LOGGED_OUT,
    DISCONNECTED,
    ERROR_DISCONNECTED,
    FORCE_DISCONNECTED,
    DATA_TRANSFER_ERROR,
    LOGINS_EXCEEDED,
    CONNECTIONS_EXCEEDED,
    TEMPORARY_BANNED,
    PERMANENTLY_BANNED,
    IP_BANNED,
    KICKED,
    WORLD_FULL,
    INVALID_LOGIN,
    RECONNECTION
}
